name: Build and Deploy with Rollback to IIS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      API_GATEWAY_PATH: 'C:\inetpub\wwwroot\SocialApiGateway'
      IDENTITY_SERVICE_PATH: 'C:\inetpub\wwwroot\IdentityService'
      USER_SERVICE_PATH: 'C:\inetpub\wwwroot\UserService'
      BACKUP_DIR: 'C:\inetpub\wwwroot\Backup'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Restore Dependencies
      run: dotnet restore Social.sln

    - name: Run Tests
      run: dotnet test Social.sln

    - name: Publish ApiGateway
      run: dotnet publish src/ApiGateways/Social.ApiGateway/Social.ApiGateway.csproj -c Release -o ./publish/ApiGateway

    - name: Publish IdentityService
      run: dotnet publish src/Services/IdentityService/IdentityService.API/IdentityService.API.csproj -c Release -o ./publish/IdentityService

    - name: Publish UserService
      run: dotnet publish src/Services/UserService/UserService.API/UserService.API.csproj -c Release -o ./publish/UserService

    - name: Stop App Pools and Wait
      run: |
        Import-Module WebAdministration

        # Stop all app pools
        $appPools = @("SocialApiGateway", "IdentityService", "UserService")
        
        foreach ($pool in $appPools) {
          if ((Get-WebAppPoolState -Name $pool).Value -eq "Started") {
            Write-Host "Stopping $pool..."
            Stop-WebAppPool -Name $pool
          }
        }

        # Wait for processes to completely stop
        Write-Host "Waiting for processes to stop..."
        Start-Sleep -Seconds 10

        # Force kill any remaining w3wp processes
        Get-Process w3wp -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
        
        # Additional wait to ensure file handles are released
        Start-Sleep -Seconds 5
      shell: powershell

    - name: Backup Existing Deployments
      run: |
        mkdir -Force $env:BACKUP_DIR
        $timestamp = Get-Date -Format "yyyyMMddHHmmss"

        # Backup with error handling
        try {
          if (Test-Path "$env:API_GATEWAY_PATH\*") {
            Compress-Archive -Path "$env:API_GATEWAY_PATH\*" -DestinationPath "$env:BACKUP_DIR\ApiGateway_$timestamp.zip" -Force
          }
          if (Test-Path "$env:IDENTITY_SERVICE_PATH\*") {
            Compress-Archive -Path "$env:IDENTITY_SERVICE_PATH\*" -DestinationPath "$env:BACKUP_DIR\IdentityService_$timestamp.zip" -Force
          }
          if (Test-Path "$env:USER_SERVICE_PATH\*") {
            Compress-Archive -Path "$env:USER_SERVICE_PATH\*" -DestinationPath "$env:BACKUP_DIR\UserService_$timestamp.zip" -Force
          }
        } catch {
          Write-Host "Backup warning: $($_.Exception.Message)"
        }
      shell: powershell

    - name: Deploy ApiGateway to IIS
      run: |
        # Safe deployment with retry mechanism
        $maxRetries = 3
        $retryCount = 0
        
        while ($retryCount -lt $maxRetries) {
          try {
            # Use robocopy for better file handling
            if (Test-Path "$env:API_GATEWAY_PATH") {
              robocopy "./publish/ApiGateway" "$env:API_GATEWAY_PATH" /MIR /R:3 /W:5 /NFL /NDL
            } else {
              Copy-Item -Recurse -Force "./publish/ApiGateway/*" "$env:API_GATEWAY_PATH\"
            }
            
            Import-Module WebAdministration
            Start-WebAppPool -Name "SocialApiGateway"
            Write-Host "ApiGateway deployed successfully"
            break
          } catch {
            $retryCount++
            Write-Host "Deployment attempt $retryCount failed: $($_.Exception.Message)"
            if ($retryCount -ge $maxRetries) {
              throw
            }
            Start-Sleep -Seconds 5
          }
        }
      shell: powershell

    - name: Deploy IdentityService to IIS
      run: |
        $maxRetries = 3
        $retryCount = 0
        
        while ($retryCount -lt $maxRetries) {
          try {
            if (Test-Path "$env:IDENTITY_SERVICE_PATH") {
              robocopy "./publish/IdentityService" "$env:IDENTITY_SERVICE_PATH" /MIR /R:3 /W:5 /NFL /NDL
            } else {
              Copy-Item -Recurse -Force "./publish/IdentityService/*" "$env:IDENTITY_SERVICE_PATH\"
            }
            
            Import-Module WebAdministration
            Start-WebAppPool -Name "IdentityService"
            Write-Host "IdentityService deployed successfully"
            break
          } catch {
            $retryCount++
            Write-Host "Deployment attempt $retryCount failed: $($_.Exception.Message)"
            if ($retryCount -ge $maxRetries) {
              throw
            }
            Start-Sleep -Seconds 5
          }
        }
      shell: powershell

    - name: Deploy UserService to IIS
      run: |
        $maxRetries = 3
        $retryCount = 0
        
        while ($retryCount -lt $maxRetries) {
          try {
            if (Test-Path "$env:USER_SERVICE_PATH") {
              robocopy "./publish/UserService" "$env:USER_SERVICE_PATH" /MIR /R:3 /W:5 /NFL /NDL
            } else {
              Copy-Item -Recurse -Force "./publish/UserService/*" "$env:USER_SERVICE_PATH\"
            }
            
            Import-Module WebAdministration
            Start-WebAppPool -Name "UserService"
            Write-Host "UserService deployed successfully"
            break
          } catch {
            $retryCount++
            Write-Host "Deployment attempt $retryCount failed: $($_.Exception.Message)"
            if ($retryCount -ge $maxRetries) {
              throw
            }
            Start-Sleep -Seconds 5
          }
        }
      shell: powershell

    - name: Wait for Services to Start
      run: |
        Write-Host "Waiting for services to fully start..."
        Start-Sleep -Seconds 15
      shell: powershell

    - name: Health Check
      run: |
        # Wait for IIS to fully initialize the applications
        Write-Host "Waiting for IIS applications to initialize..."
        Start-Sleep -Seconds 20
        
        $apiGatewayUrl = "https://api.iscsocial.com/health"
        $identityUrl = "https://api.iscsocial.com/identity/health"
        $userUrl = "https://api.iscsocial.com/user/health"

        $urls = @($apiGatewayUrl, $identityUrl, $userUrl)
        $maxRetries = 6
        $retryDelay = 15
        $allHealthy = $true

        foreach ($url in $urls) {
          $success = $false
          Write-Host "Starting health check for $url"
          
          for ($i = 1; $i -le $maxRetries; $i++) {
            try {
              Write-Host "Health check attempt $i/$maxRetries for $url"
              
              # Add more detailed error handling
              $response = Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 45 -ErrorAction Stop
              
              Write-Host "Response Status: $($response.StatusCode)"
              Write-Host "Response Content: $($response.Content)"
              
              if ($response.StatusCode -eq 200) {
                # Check if response contains health status
                if ($response.Content -match '"status"\s*:\s*"Healthy"' -or $response.Content -notmatch '"status"') {
                  Write-Host "SUCCESS: Health check passed for $url"
                  $success = $true
                  break
                } else {
                  Write-Host "WARNING: Health check returned non-healthy status for $url"
                }
              } else {
                Write-Host "WARNING: Health check returned status code $($response.StatusCode) for $url"
              }
            } catch {
              Write-Host "Health check attempt $i failed for $url"
              Write-Host "Error: $($_.Exception.Message)"
              
              # Check if it's a connection error vs application error
              if ($_.Exception.Message -match "timeout|connection|network") {
                Write-Host "Network/Connection error detected"
              } elseif ($_.Exception.Message -match "500|502|503|504") {
                Write-Host "Application error detected"
              }
            }
            
            if ($i -lt $maxRetries) {
              Write-Host "Waiting $retryDelay seconds before retry..."
              Start-Sleep -Seconds $retryDelay
            }
          }
          
          if (-not $success) {
            Write-Host "ERROR: Health check failed for $url after $maxRetries attempts"
            $allHealthy = $false
          }
        }
        
        if (-not $allHealthy) {
          Write-Host "ERROR: One or more health checks failed"
          exit 1
        }
        
        Write-Host "SUCCESS: All health checks passed"
      shell: powershell

    - name: Rollback if Health Check Fails
      if: failure()
      run: |
        Write-Host "Rolling back to previous version..."

        Import-Module WebAdministration

        # Stop app pools
        $appPools = @("SocialApiGateway", "IdentityService", "UserService")
        
        foreach ($pool in $appPools) {
          if ((Get-WebAppPoolState -Name $pool).Value -eq "Started") {
            Write-Host "Stopping $pool for rollback..."
            Stop-WebAppPool -Name $pool
          }
        }

        # Wait and kill processes
        Start-Sleep -Seconds 10
        Get-Process w3wp -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 5

        # Find latest backups
        $apiBackup = Get-ChildItem $env:BACKUP_DIR | Where-Object { $_.Name -like "ApiGateway*" } | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        $identityBackup = Get-ChildItem $env:BACKUP_DIR | Where-Object { $_.Name -like "IdentityService*" } | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        $userBackup = Get-ChildItem $env:BACKUP_DIR | Where-Object { $_.Name -like "UserService*" } | Sort-Object LastWriteTime -Descending | Select-Object -First 1

        # Rollback with robocopy
        $rollbackSuccess = $true
        
        try {
          if ($apiBackup) {
            Write-Host "Restoring ApiGateway from backup..."
            $tempDir = "$env:TEMP\ApiGateway_restore"
            Expand-Archive -Path "$env:BACKUP_DIR\$($apiBackup.Name)" -DestinationPath $tempDir -Force
            $result = robocopy $tempDir "$env:API_GATEWAY_PATH" /MIR /R:3 /W:5 /NFL /NDL
            if ($LASTEXITCODE -ge 8) { $rollbackSuccess = $false }
            Remove-Item -Recurse -Force $tempDir -ErrorAction SilentlyContinue
          }

          if ($identityBackup) {
            Write-Host "Restoring IdentityService from backup..."
            $tempDir = "$env:TEMP\IdentityService_restore"
            Expand-Archive -Path "$env:BACKUP_DIR\$($identityBackup.Name)" -DestinationPath $tempDir -Force
            $result = robocopy $tempDir "$env:IDENTITY_SERVICE_PATH" /MIR /R:3 /W:5 /NFL /NDL
            if ($LASTEXITCODE -ge 8) { $rollbackSuccess = $false }
            Remove-Item -Recurse -Force $tempDir -ErrorAction SilentlyContinue
          }

          if ($userBackup) {
            Write-Host "Restoring UserService from backup..."
            $tempDir = "$env:TEMP\UserService_restore"
            Expand-Archive -Path "$env:BACKUP_DIR\$($userBackup.Name)" -DestinationPath $tempDir -Force
            $result = robocopy $tempDir "$env:USER_SERVICE_PATH" /MIR /R:3 /W:5 /NFL /NDL
            if ($LASTEXITCODE -ge 8) { $rollbackSuccess = $false }
            Remove-Item -Recurse -Force $tempDir -ErrorAction SilentlyContinue
          }

          # Start app pools
          foreach ($pool in $appPools) {
            Write-Host "Starting $pool after rollback..."
            Start-WebAppPool -Name $pool
          }

          if ($rollbackSuccess) {
            Write-Host "Rollback completed successfully"
            # Don't exit with error code if rollback was successful
          } else {
            Write-Host "Rollback completed with some warnings"
          }
        } catch {
          Write-Host "Rollback error: $($_.Exception.Message)"
          # Even if rollback fails, don't exit with error since we tried our best
        }
      shell: powershell
      continue-on-error: true
