name: Build and Deploy with Rollback to IIS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      API_GATEWAY_PATH: 'C:\inetpub\wwwroot\SocialApiGateway'
      IDENTITY_SERVICE_PATH: 'C:\inetpub\wwwroot\IdentityService'
      USER_SERVICE_PATH: 'C:\inetpub\wwwroot\UserService'
      BACKUP_DIR: 'C:\inetpub\wwwroot\Backup'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Restore Dependencies
      run: dotnet restore Social.sln

    - name: Run Tests
      run: dotnet test Social.sln

    - name: Publish ApiGateway
      run: dotnet publish src/ApiGateways/Social.ApiGateway/Social.ApiGateway.csproj -c Release -o ./publish/ApiGateway

    - name: Publish IdentityService
      run: dotnet publish src/Services/IdentityService/IdentityService.API/IdentityService.API.csproj -c Release -o ./publish/IdentityService

    - name: Publish UserService
      run: dotnet publish src/Services/UserService/UserService.API/UserService.API.csproj -c Release -o ./publish/UserService

    - name: Stop App Pools and Wait
      run: |
        Import-Module WebAdministration

        $appPools = @("SocialApiGateway", "IdentityService", "UserService")
        foreach ($pool in $appPools) {
          if ((Get-WebAppPoolState -Name $pool).Value -eq "Started") {
            Stop-WebAppPool -Name $pool
          }
        }
        Start-Sleep -Seconds 10
        Get-Process w3wp -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 5
      shell: powershell

    - name: Backup Existing Deployments
      run: |
        mkdir -Force $env:BACKUP_DIR
        $timestamp = Get-Date -Format "yyyyMMddHHmmss"

        if (Test-Path "$env:API_GATEWAY_PATH\*") {
          Compress-Archive -Path "$env:API_GATEWAY_PATH\*" -DestinationPath "$env:BACKUP_DIR\ApiGateway_$timestamp.zip" -Force
        }
        if (Test-Path "$env:IDENTITY_SERVICE_PATH\*") {
          Compress-Archive -Path "$env:IDENTITY_SERVICE_PATH\*" -DestinationPath "$env:BACKUP_DIR\IdentityService_$timestamp.zip" -Force
        }
        if (Test-Path "$env:USER_SERVICE_PATH\*") {
          Compress-Archive -Path "$env:USER_SERVICE_PATH\*" -DestinationPath "$env:BACKUP_DIR\UserService_$timestamp.zip" -Force
        }
      shell: powershell

    - name: Deploy ApiGateway to IIS
      run: |
        $result = robocopy "./publish/ApiGateway" "$env:API_GATEWAY_PATH" /MIR /R:3 /W:5 /NFL /NDL
        $exitCode = $LASTEXITCODE
        if ($exitCode -lt 8) {
          Write-Host "Robocopy success: $exitCode"
        } else {
          Write-Host "Robocopy failed: $exitCode"
          exit $exitCode
        }

        Import-Module WebAdministration
        Start-WebAppPool -Name "SocialApiGateway"
      shell: powershell

    - name: Deploy IdentityService to IIS
      run: |
        $result = robocopy "./publish/IdentityService" "$env:IDENTITY_SERVICE_PATH" /MIR /R:3 /W:5 /NFL /NDL
        $exitCode = $LASTEXITCODE
        if ($exitCode -lt 8) {
          Write-Host "Robocopy success: $exitCode"
        } else {
          Write-Host "Robocopy failed: $exitCode"
          exit $exitCode
        }

        Import-Module WebAdministration
        Start-WebAppPool -Name "IdentityService"
      shell: powershell

    - name: Deploy UserService to IIS
      run: |
        $result = robocopy "./publish/UserService" "$env:USER_SERVICE_PATH" /MIR /R:3 /W:5 /NFL /NDL
        $exitCode = $LASTEXITCODE
        if ($exitCode -lt 8) {
          Write-Host "Robocopy success: $exitCode"
        } else {
          Write-Host "Robocopy failed: $exitCode"
          exit $exitCode
        }

        Import-Module WebAdministration
        Start-WebAppPool -Name "UserService"
      shell: powershell

    - name: Wait for Services to Start
      run: Start-Sleep -Seconds 15
      shell: powershell

    - name: Health Check
      run: |
        Start-Sleep -Seconds 20

        $urls = @(
          "https://api.iscsocial.com/health",
          "https://api.iscsocial.com/identity/health",
          "https://api.iscsocial.com/user/health"
        )

        $allHealthy = $true
        foreach ($url in $urls) {
          $success = $false
          for ($i = 1; $i -le 6; $i++) {
            try {
              $response = Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 45
              if ($response.StatusCode -eq 200 -and ($response.Content -match '"status"\s*:\s*"Healthy"' -or $response.Content -notmatch '"status"')) {
                $success = $true
                break
              }
            } catch {}
            Start-Sleep -Seconds 15
          }
          if (-not $success) {
            $allHealthy = $false
          }
        }
        if (-not $allHealthy) { exit 1 }
      shell: powershell

    - name: Rollback if Health Check Fails
      if: failure()
      run: |
        Import-Module WebAdministration

        $appPools = @("SocialApiGateway", "IdentityService", "UserService")
        foreach ($pool in $appPools) {
          if ((Get-WebAppPoolState -Name $pool).Value -eq "Started") {
            Stop-WebAppPool -Name $pool
          }
        }

        Start-Sleep -Seconds 10
        Get-Process w3wp -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 5

        $rollbackSuccess = $true

        $apiBackup = Get-ChildItem $env:BACKUP_DIR | Where-Object { $_.Name -like "ApiGateway*" } | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        $identityBackup = Get-ChildItem $env:BACKUP_DIR | Where-Object { $_.Name -like "IdentityService*" } | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        $userBackup = Get-ChildItem $env:BACKUP_DIR | Where-Object { $_.Name -like "UserService*" } | Sort-Object LastWriteTime -Descending | Select-Object -First 1

        if ($apiBackup) {
          Expand-Archive -Path "$env:BACKUP_DIR\$($apiBackup.Name)" -DestinationPath "$env:TEMP\ApiGateway_restore" -Force
          $result = robocopy "$env:TEMP\ApiGateway_restore" "$env:API_GATEWAY_PATH" /MIR /R:3 /W:5 /NFL /NDL
          if ($LASTEXITCODE -ge 8) { $rollbackSuccess = $false }
          Remove-Item -Recurse -Force "$env:TEMP\ApiGateway_restore"
        }
        if ($identityBackup) {
          Expand-Archive -Path "$env:BACKUP_DIR\$($identityBackup.Name)" -DestinationPath "$env:TEMP\IdentityService_restore" -Force
          $result = robocopy "$env:TEMP\IdentityService_restore" "$env:IDENTITY_SERVICE_PATH" /MIR /R:3 /W:5 /NFL /NDL
          if ($LASTEXITCODE -ge 8) { $rollbackSuccess = $false }
          Remove-Item -Recurse -Force "$env:TEMP\IdentityService_restore"
        }
        if ($userBackup) {
          Expand-Archive -Path "$env:BACKUP_DIR\$($userBackup.Name)" -DestinationPath "$env:TEMP\UserService_restore" -Force
          $result = robocopy "$env:TEMP\UserService_restore" "$env:USER_SERVICE_PATH" /MIR /R:3 /W:5 /NFL /NDL
          if ($LASTEXITCODE -ge 8) { $rollbackSuccess = $false }
          Remove-Item -Recurse -Force "$env:TEMP\UserService_restore"
        }

        foreach ($pool in $appPools) {
          Start-WebAppPool -Name $pool
        }

        if ($rollbackSuccess) {
          Write-Host "Rollback completed successfully"
        } else {
          Write-Host "Rollback completed with warnings"
        }
      shell: powershell
      continue-on-error: true
